security:
    providers:
        in_memory:
            memory:
              users:
                restapi: { password: secretpw, roles: [ 'ROLE_API' ] }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
      ROLE_API: ROLE_USER

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
            http_basic:
              realm: "Demo REST API (username: restapi, password: secretpw)"
